collections:
  projects:
    output: false
  posts:
    output: false
  fossfund:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      image: https://opensource.azureedge.net/assets/images/social-card.png
      layout: default
